/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package _05.queue;

public class App {
    public String getGreeting() {
        return "안녕하세요, 맑은 고딕입니다!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
